-- ============================================================
-- Catalog Service — initial schema (CQRS write + read model)
-- Search path đã được set thành "catalog" cho role svc_catalog.
-- ============================================================

-- ---------- Write model: products ----------
CREATE TABLE IF NOT EXISTS products (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ma_sp           BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    ten_sp          VARCHAR(300) NOT NULL,
    loai_sp         VARCHAR(50)  NOT NULL,
    gia_ban_dau     NUMERIC(15,0) NOT NULL CHECK (gia_ban_dau >= 0),
    gia_giam_gia    NUMERIC(15,0) NOT NULL DEFAULT 0 CHECK (gia_giam_gia >= 0),
    trong_luong     NUMERIC(7,2),
    ham_luong       VARCHAR(20),
    loai_da         VARCHAR(50),
    mau_da          VARCHAR(50),
    gioi_tinh       VARCHAR(20),
    thuong_hieu     VARCHAR(100),
    description     TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                    CHECK (status IN ('ACTIVE','ARCHIVED')),
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_products_loai_sp   ON products(loai_sp);
CREATE INDEX IF NOT EXISTS idx_products_status    ON products(status);

-- ---------- Write model: product_images ----------
CREATE TABLE IF NOT EXISTS product_images (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id   UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url    VARCHAR(500) NOT NULL,
    sort_order   INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_product_images_product ON product_images(product_id);

-- ---------- Read model: product_view (denormalized JSONB + tsvector) ----------
CREATE TABLE IF NOT EXISTS product_view (
    product_id   UUID PRIMARY KEY,
    doc          JSONB NOT NULL,
    search_tsv   tsvector,
    loai_sp      VARCHAR(50),
    status       VARCHAR(20),
    gia_hien_tai NUMERIC(15,0),  -- = gia_giam_gia > 0 ? gia_giam_gia : gia_ban_dau
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pv_tsv      ON product_view USING GIN(search_tsv);
CREATE INDEX IF NOT EXISTS idx_pv_loai     ON product_view(loai_sp);
CREATE INDEX IF NOT EXISTS idx_pv_status   ON product_view(status);
CREATE INDEX IF NOT EXISTS idx_pv_gia      ON product_view(gia_hien_tai);

-- Trigger updated_at on products
CREATE OR REPLACE FUNCTION catalog.touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION catalog.touch_updated_at();
